name: CI / CD 

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        