name: CI / CD 

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set branch
        id: set_branch
        run: echo "::set-output name=branch::main"
      - name: Print out branch
        run: echo "output=${{ steps.set_branch.outputs.branch }}"
      - name: Create release
        if: contains(steps.set_branch.outputs.branch,  'main')
        uses: softprops/action-gh-release@v1
        